---
- name: Create the channel
  hosts: localhost
  vars_files:
    - 00-common-vars.yml
    - 02-org1-vars.yml
  tasks:
    - name: Create certificate authority with custom resources and storage
      ibm.blockchain_platform.certificate_authority:
        state: present
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: basic
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        name: "{{ org1_ca_name }}"
        replicas: 2
        config_override:
          ca:
            debug: false
            affiliations:
              ibp: []
            registry:
              maxenrollments: -1
              identities:
              - name: "{{ organization_admin_enrollment_id }}"
                pass: "{{ organization_admin_enrollment_secret }}"
                type: admin
              - name: "{{ peer_enrollment_id }}"
                pass: "{{ peer_enrollment_secret }}"
                type: peer
              - name: "{{ ca_admin_enrollment_id }}"
                pass: "{{ ca_admin_enrollment_secret }}"
                type: client
                attrs:
                  hf.Registrar.Roles: "*"
                  hf.Registrar.DelegateRoles: "*"
                  hf.Revoker: true
                  hf.IntermediateCA: true
                  hf.GenCRL: true
                  hf.Registrar.Attributes: "*"
                  hf.AffiliationMgr: true
            db:
              type: postgres
              datasource: "{{ datasource }}"
              tls:
                enabled: true
                certfiles:
                - "{{ certfiles }}"
        resources:
          ca:
            requests:
              cpu: 1000m
              memory: 400M