---
- name: Create the channel
  hosts: localhost
  vars_files:
    - 00-common-vars.yml
    - ordering-org-vars.yml
  tasks:
    - name: Create certificate authority with custom resources and storage
      ibm.blockchain_platform.certificate_authority:
        state: present
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: basic
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        name: "{{ ca_name }}"
        replicas: 2
        config_override:
          ca:
            debug: false
            affiliations:
              ibp: []
            registry:
              maxenrollments: -1
              identities:
              - name: "{{ organization_admin_enrollment_id }}"
                pass: "{{ organization_admin_enrollment_secret }}"
                type: admin
              - name: "{{ ordering_service_enrollment_id }}"
                pass: "{{ ordering_service_enrollment_secret }}"
                type: orderer
              - name: "{{ ca_admin_enrollment_id }}"
                pass: "{{ ca_admin_enrollment_secret }}"
                type: client
                attrs:
                  hf.Registrar.Roles: "*"
                  hf.Registrar.DelegateRoles: "*"
                  hf.Revoker: true
                  hf.IntermediateCA: true
                  hf.GenCRL: true
                  hf.Registrar.Attributes: "*"
                  hf.AffiliationMgr: true
            db:
              type: postgres
              datasource: "{{ datasource }}"
              tls:
                enabled: true
                certfiles:
                - "{{ certfiles }}"
          # tlsca:
          #   db:
          #     type: postgres
          #     datasource: host=8e91e321-ea1d-4171-8eeb-eddf2b51383e.bkvfvtld0lmh0umkfi70.databases.appdomain.cloud port=30419 user=ibm_cloud_a99dcddb_942d_407f_8bae_fccadad45e13 password=2965f67ff03d18f3742e76b108fb0a76844c68a76d0d7dbfbf42dda7e1aa3bdb dbname=fabricca sslmode=verify-full
          #     tls:
          #       enabled: true
          #       certfiles:
          #        - "-----BEGIN CERTIFICATE-----\nMIIDDzCCAfegAwIBAgIJANEH58y2/kzHMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV\nBAMME0lCTSBDbG91ZCBEYXRhYmFzZXMwHhcNMTgwNjI1MTQyOTAwWhcNMjgwNjIy\nMTQyOTAwWjAeMRwwGgYDVQQDDBNJQk0gQ2xvdWQgRGF0YWJhc2VzMIIBIjANBgkq\nhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lpaQGzcFdGqeMlmqjffMPpIQhqpd8qJ\nPr3bIkrXJbTcJJ9uIckSUcCjw4Z/rSg8nnT13SCcOl+1to+7kdMiU8qOWKiceYZ5\ny+yZYfCkGaiZVfazQBm45zBtFWv+AB/8hfCTdNF7VY4spaA3oBE2aS7OANNSRZSK\npwy24IUgUcILJW+mcvW80Vx+GXRfD9Ytt6PRJgBhYuUBpgzvngmCMGBn+l2KNiSf\nweovYDCD6Vngl2+6W9QFAFtWXWgF3iDQD5nl/n4mripMSX6UG/n6657u7TDdgkvA\n1eKI2FLzYKpoKBe5rcnrM7nHgNc/nCdEs5JecHb1dHv1QfPm6pzIxwIDAQABo1Aw\nTjAdBgNVHQ4EFgQUK3+XZo1wyKs+DEoYXbHruwSpXjgwHwYDVR0jBBgwFoAUK3+X\nZo1wyKs+DEoYXbHruwSpXjgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC\nAQEAJf5dvlzUpqaix26qJEuqFG0IP57QQI5TCRJ6Xt/supRHo63eDvKw8zR7tlWQ\nlV5P0N2xwuSl9ZqAJt7/k/3ZeB+nYwPoyO3KvKvATunRvlPBn4FWVXeaPsG+7fhS\nqsejmkyonYw77HRzGOzJH4Zg8UN6mfpbaWSsyaExvqknCp9SoTQP3D67AzWqb1zY\ndoqqgGIZ2nxCkp5/FXxF/TMb55vteTQwfgBy60jVVkbF7eVOWCv0KaNHPF5hrqbN\ni+3XjJ7/peF3xMvTMoy35DcT3E2ZeSVjouZs15O90kI3k2daS2OHJABW0vSj4nLz\n+PQzp/B9cQmOO8dCe049Q3oaUA==\n-----END CERTIFICATE-----\n"
                # client:
                #     certfile: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyVENDQWNFQ0NRREVoT3JtVklxb2tqQU5CZ2txaGtpRzl3MEJBUXNGQURBa01TSXdJQVlEVlFRRERCbGsKWVhSaFltRnpaWE11WVhCd1pHOXRZV2x1TG1Oc2IzVmtNQjRYRFRJd01EZ3dNekU1TWpVd01sb1hEVEl4TURndwpNekU1TWpVd01sb3dPVEUzTURVR0ExVUVBd3d1YVdKdFgyTnNiM1ZrWDJFNU9XUmpaR1JpWHprME1tUmZOREEzClpsODRZbUZsWDJaalkyRmtZV1EwTldVeE16Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFOa282ODBUYWdtbkc5WkFzdW5ieFVpUVVKQlNsdm5NelNuSDhKeWExTXpYRlJEdmovVUx3dU8rNXVsVApXQ3MyNW1idFZyZ3c2NEtxWlUwaFZLazUyWEJlZ0pORmFCNi81ZmZkUG1zSVlQdmgzT2crZXNyMmdNYWZaYlFqClhZUGVsbjFjOGxhZmc4WE1JRWY3cHQ3NE1weGk5Sm5HN1FxNkZYREJwbGxEUjRGa1JaTnNSWURpcllERzhzZkcKY3Zrbm80aVB5SGVMZi80SmZnR3d6ODZBL0lTSUtPekF4WC9LelNyWElETitIenJlNWU2S0M3MnloOVJnNksvSApTQXk2WlRDcGJ6dTk4VXh5Q0l4Qkh5VFpzSW1peE9uMHRCZTFnRDVhVE9YSThZN0ZsSnltK2ZLT3ZqTzh4REhxCitSVlpKOFZzVWZXSXRlNjF5N0duYVR5MlVQY0NBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQW5mWEYKYW41WnZWMTl6QXZ6ZlNHbVBOUXdBczhjenVCQWJOdlhBTDYreWtKd1FOUHBROTJIMXNsWTdpRmlkcVpmWGFTVAp1RW56TDFoOS81MGs5MVNscVJpTTFvdUpIOHJiV20zMzNmWEFrQ1pWSlRDSGFlRzk1Mm96NDBjQnlxRW8xUFo4CjdTbWduZkZwWjZQdGV5VTFYMFJCOTZlRlM0V09Qc0RPbnVBMXh1V21BaWdTL0pBSDdXV2xGeEZiM3lmdnVYMEwKY01LY3kvMVROSlA3YTQ1L2kwUEJHU3FOSzk0c21uUTYxWlFSNGxmMHpVZG1wWTJLZU9UbzdBM28vQjdMeEhwSwpQK0tkV3RWc2s3SXMxVTY1aVA5V05iYS85N2dKUXNNM1U0VS9sNlp5VGp4bU54TlE2ZTZwWlA1MVZXVmZSU3RRCi8valZVRlhSZFhwb3J4THRnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
                #     keyfile: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRFpLT3ZORTJvSnB4dlcKUUxMcDI4VklrRkNRVXBiNXpNMHB4L0NjbXRUTTF4VVE3NC8xQzhManZ1YnBVMWdyTnVabTdWYTRNT3VDcW1WTgpJVlNwT2Rsd1hvQ1RSV2dlditYMzNUNXJDR0Q3NGR6b1Bucks5b0RHbjJXMEkxMkQzcFo5WFBKV240UEZ6Q0JICis2YmUrREtjWXZTWnh1MEt1aFZ3d2FaWlEwZUJaRVdUYkVXQTRxMkF4dkxIeG5MNUo2T0lqOGgzaTMvK0NYNEIKc00vT2dQeUVpQ2pzd01WL3lzMHExeUF6Zmg4NjN1WHVpZ3U5c29mVVlPaXZ4MGdNdW1Vd3FXODd2ZkZNY2dpTQpRUjhrMmJDSm9zVHA5TFFYdFlBK1dremx5UEdPeFpTY3B2bnlqcjR6dk1ReDZ2a1ZXU2ZGYkZIMWlMWHV0Y3V4CnAyazh0bEQzQWdNQkFBRUNnZ0VBZTZsWjNnWllNL2I5V3h5c3hZOW80TkdOanlINDUzZEF2YklseW9oQTlnVGsKOGlmNWlrbVFTYkRFUGNwQVF4dVlTTFNPMVlUR0dEcUFSVlBkcWlCUE9qWVdjY2JzYTlaTFZzS2VjTVRzdFlNQgpFUi9EUFNEeVpDa1ErV3ZLTFBYc0xLZHBPUHJOUnkzZWxCOHgvM2JIRzFjZWd4Tk1tUGN1am04NEUwekV3MkVSCnk4Ny9ER0l1TU1sSk15STBFMHhkSWlza25ya2NYemVaOG5qQUJJSVJ5Zy94SFA1SDZ0czNoVWZ4QVBWOFRwYk0KZExMYWRLNDNwUzgzNEJleXBGWFA5RkMzOHgvdU5RTTlYcVpiUzFWbHpsbzZGSGo1Vk1JdWRCU284dGhsZG5yYwpRVWREMGNvdms0TkNIc29YbmxQTm90UFJJMFZ0U1ZXeXYwMVZDRHVHZ1FLQmdRRHZuUG9KMkFlSVdJek5nNFRGClN4cDJHM05WQmdXck9oZ3BOQVVvNmNKOGppeS91UWVvU0dFVGJuaUNXSXVLbGZFdDRTa1ZXeC9RSEVzaHdMRVkKSm9CUWdtc28xYU43NDRORDJFcVBwbkk4ejJVSVFtbndCSzNhMGYzMXpMN25jc3lOcnNIQ1VNYnd0R0REM3daRgplOG9OM2owWXNxUzlSTkd3MEYyK3Z4amVqd0tCZ1FEb0F0ZktVT0ZVSEh5eWl6NWtLWVZvMEJ0Y21oZWVEUkR1CnFkOVVLSUNxV296VlJuNi9HRlROR3BpK0srYXc3c1Y1TWNSTGpwUmpuK1JvZnV2cHkwZC9CR1VuUWVLeDJhTzgKU3p1VkJsUTh4U2xSMzR6ZHhhODN2Skd6WjJUYnZ3SmthUzNrM3Q4NXlQd0p2NkZTNTNYaXROby9UZEloOEg4MgpxeEdwZHZpYkdRS0JnSHN3dTZTZitvOXc1ME1wNFBNR1A5NkZFbkNlSGdBQWFEZVcxU2hKdG9JUEhwYWJiSUpxClkrNTNsMkY4WUpHcHNVdWpQVm9MZFhtcmNqMHlNbHAyUVBZamR6Q1JWZkgxOEtESzdOcVorcFdsRXc2Q0JyRXQKMXF4djFoK3ZXbDdvT0o2SFFIckV5T01yK2F2NlYrRVZXYlp6a2ZuR3JzZllQKzZsMGV5bGx3V2xBb0dBVmxnbwpndXpTendEREQ1ZHVvc3dwRURiUzJBV280SE13YUFIa1VXZTVhcXpFV09NaGJIRGJybkZGZ3hESGkvVnduSWYrCjY3ZW1WZVU5bGY0V1FpNGE3NVJ0S00wR1Z2WU9UNWNZRjRBQmZaUktxbU91QXlMODhKdEhCaU5tajdsb1pJSVkKU0dNQlpIbitBb3JFdVJ2VzdZWXM2djVGUThoREw4OCtoWGozVUpFQ2dZQXRzL1RGUDgwTGV4QVc1REdiNjZDVgpiWGxEVEsxaGJicVJSOVZJTzlSWkx4MTZyOHNoeVJlM3ZLV3dRY09WWi9PamdnWXA3bjc2YUZXRUhDOW5hOENWCjJHdDlYdWxVTzhseElvcktHN2djalJvQzJCWG5LUHdjcFZhRE1LU2dLMitJSkF4M2dLdDBqVzVUT09yTmVyM3IKSmFLZUVEc0tFQkREaWlNSEs0Ym15dz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
        resources:
          ca:
            requests:
              cpu: 1000m
              memory: 400M